---
- name: Build BGP underlay configuration
  template: src=underlay.j2 dest=/tmp/{{ inventory_hostname }}.conf
- name: Deploy BGP underlay configuration to device ... please wait
  juniper_junos_config:
    load: 'merge'
    src: "/tmp/{{ inventory_hostname }}.conf"
    provider: "{{ connection_settings }}"
    format: text
    logfile: /tmp/changes.log
