---
- name: Get device facts
  hosts: all
  vars:
    connection_settings:
      host: "{{ ansible_ssh_host }}"
      port: "{{ ansible_ssh_port }}"
    ansible_python_interpreter: "python"
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Get facts using galaxy module
      juniper_junos_facts:
        provider: "{{ connection_settings }}"
      register: facts
    - name: Display facts
      debug:
        msg: "Device {{ facts.ansible_facts.junos.hostname }} runs version {{ facts.ansible_facts.junos.junos_info.fpc0.text }}"
      when: facts.ansible_facts.junos is defined

