---
- name: Create demo lab Juniper
  hosts: qfx
  vars:
    connection_settings:
      host: "{{ ansible_ssh_host }}"
      port: "{{ ansible_ssh_port }}"
  connection: local
  gather_facts: no
  roles:
    - role: Juniper.junos
      tags: [ bgp, ospf ]
    - role: common
      tags: [ bgp, ospf ]
    - role: underlay_bgp
      tags: [ bgp ]
    - role: check_bgp
      tags: [ bgp ]
