---
- name: Create demo lab Juniper
  hosts: qfx
  vars:
    connection_settings:
      host: "{{ ansible_ssh_host }}"
      port: "{{ ansible_ssh_port }}"
  connection: local
  gather_facts: no
  roles:
    - role: Juniper.junos
      tags: [ bgp, ospf, save_rescue, load_rescue ]
    - role: save_rescue
      tags: [ save_rescue ]
    - role: load_rescue
      tags: [ load_rescue ]
    - role: common
      tags: [ bgp, ospf ]
    - role: underlay_bgp
      tags: [ bgp ]
    - role: check_bgp
      tags: [ bgp ]
    - role: underlay_ospf
      tags: [ ospf ]
    - role: check_ospf
      tags: [ ospf ]
