---
- name: Create demo lab Juniper
  hosts: qfx
  vars:
    connection_settings:
      host: "{{ ansible_ssh_host }}"
      port: "{{ ansible_ssh_port }}"
    ansible_python_interpreter: "/usr/bin/python3"
  connection: local
  gather_facts: no
  roles:
    - role: Juniper.junos
    - role: save_rescue
      tags: [ save_rescue ]
    - role: load_rescue
      tags: [ load_rescue ]
    - role: common
      tags: [ bgp, ospf ]
    - role: underlay_bgp
      tags: [ bgp ]
    - role: check_bgp
      tags: [ check_bgp ]
    - role: underlay_ospf
      tags: [ ospf ]
    - role: check_ospf
      tags: [ check_ospf ]
