---
- name: Build common configuration
  template: src=common.j2 dest=/tmp/{{ inventory_hostname }}.conf
- name: Deploy common configuration to device ... please wait
  juniper_junos_config:
    load: 'merge'
    src: "/tmp/{{ inventory_hostname }}.conf"
    provider: "{{ connection_settings }}"    
    format: text
    logfile: /tmp/changes.log
