system:
  hostname: spine01
  loopback_ip: 1.1.1.1

underlay:
  local:
    asn: 60001
  neighbors:
    - interface: em5
      name: leaf01
      asn: 60011
      peer_ip: "{{ p2p.link1.2 }}"
      peer_loopback: 1.1.1.11
      local_ip: "{{ p2p.link1.1 }}"
    - interface: em6
      name: leaf02
      asn: 60012
      peer_ip: "{{ p2p.link3.2 }}"
      peer_loopback: 1.1.1.12
      local_ip: "{{ p2p.link3.1 }}"
